adding accuracy, attack and defense bonuses and 1-handed penalty
smilediver/UrwObjDump pull request #1
Opened 2017-03-20 21:07 UTC by fabioticconi

2017-03-20 21:08 UTC, fabioticconi commented
I'm not sure if you are still playing URW.. but your tool is still pretty much the best. There's another one, but the source code has been lost - which is bad for future versions.

So I updated yours a bit.

2017-03-22 14:37 UTC, smilediver requested changes

2017-03-22 14:37 UTC, Smilediver commented on Program.cs
> +		public byte defenceBonus;
Nitpicking but it's "defense" :)

2017-03-22 14:37 UTC, Smilediver commented on Program.cs
> +			}
Forgot "else data.ReadByte();"? Cause I'd assume you need to skip a byte for non weapons.

2017-03-22 14:38 UTC, Smilediver commented
I play it on and off. :) If you can fix that else thing, I'd be glad to accept the changes. Awesome stuff otherwise!

2017-03-22 14:40 UTC, fabioticconi commented on Program.cs
> +		public byte defenceBonus;
Depends where you live! I'm more of a British English guy, he :P

2017-03-22 15:46 UTC, fabioticconi commented on Program.cs
> +			}
You are right, I will add it. That "if" was a last minute addition (superfluous really) which I hadn't tested.

2017-03-23 17:59 UTC, fabioticconi commented
This time I tested it, should be OK ;)

2019-08-23 11:41 UTC, merged